import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "Kelompok Tani Agro Lestari",
  title: "Melon Premium Lampung Timur – Agro Lestari",
  description:
    "Temukan kemurnian dan kesegaran Melon Premium langsung dari ladang terbaik Lampung Timur. Ditanam dengan teknik ramah lingkungan oleh Kelompok Tani Agro Lestari, kami hadirkan rasa manis alami dan kualitas buah unggulan untuk Indonesia.",
  origin: "https://www.agrolestarifarm.my.id",
  keywords: [
    "Melon Premium",
    "Lampung Timur",
    "Pertanian Organik",
    "Kelompok Tani",
    "Agro Lestari",
    "Buah Segar",
    "Petani Lokal",
    "Hasil Tani Berkualitas",
    "Agribisnis",
    "Komunitas Tani",
    "Hidroponik",
    "Greenhouse",
    "Sustainable Farming",
    "Pertanian Berkelanjutan",
    "Golden Melon",
    "Melon Manis",
    "Melon Segar",
    "Melon Organik",
    "Melon Lampung",
    "Melon Indonesia",
    "Tanaman Buah Tropis",
    "Melon Hijau",
    "Melon Berkualitas",
    "Pertanian Berkelanjutan Lampung",
    "Budidaya Melon Hidroponik",
    "Melon Sumatera",
    "Melon Organik Lampung",
    "Pupuk Organik Melon",
    "Budidaya Melon Greenhouse",
    "Melon Berkelanjutan",
    "Melon Segar Lampung",
    "Melon Premium Sumatera",
    "Kebun Melon Lampung Timur",
    "Pertanian Modern Lampung",
    "Farm-to-Table Melon",
    "Teknik Budidaya Melon",
    "Melon Manis Lampung",
    "Greenhouse Melon Lampung",
    "Petani Melon Lampung",
    "Melon Lokal Berkualitas",
    "Sumber Buah Organik",
    "Pasar Melon Indonesia",
    "Agroindustri Lampung",
    "Teknologi Pertanian Melon",
    "Melon Segar Berkualitas",
    "Pasar Melon Sumatera",
  ],
  og: "https://www.agrolestarifarm.my.id/marketing/hero-image.png",
  creator: {
    name: "Kelompok Tani Agro Lestari",
    url: "https://www.agrolestarifarm.my.id/about",
  },
  socials: {
    whatsapp: "https://wa.me/6281369674457",
  },
};
